### ISSUE TITLE
Curated

### ISSUE THREAD

**Issue by enam** [piepdx/pie-cookbook#3]
I am adding this because it applies to our venture of curated co-working, I am curious about the process you used for a curated co-working location (back when that described what you were). Our goal is one of high quality curated membership. 
I imagine the topic of curation applies to the incubator situation as well and that many backers would be interested to get a window into the process for soliciting and vetting members/participants that you have found to be most successful.

**Comment by turoczy** [comment]
Thanks for suggesting this! We definitely have plans to touch on that experiment in PIE's history but we'll make sure to be more explicit about how the curated coworking worked. I think the most important thing we learned is that coworking and community development, rather than being complementary, are often at odds with one another.

**Comment by turoczy** [comment]
Added this to Notes. https://github.com/piepdx/pie-cookbook/blob/master/notes/community/curated-coworking.md
