### ISSUE TITLE
Topic: 404 

### ISSUE THREAD

**Issue by turoczy** [piepdx/pie-cookbook#82]
Describe the origins and outcomes of the 404 contest

**Comment by rgleeson** [comment]
404: Origins

Despite each company's accelerator experience being its own special 'world of hurt', we've learned over the years that the collective morale of the class has its own fairly predictable peaks and troughs. We didn't realize that in our first year, but there it was - two-thirds of the way through the program the punch list of fixes and to-do's seemed to be getting longer (and redder) and the high of collective world-beating ("yay! we're in! there's a coffee machine!") had faded to a semi-sullen slog. Stuff was getting done, but the joy was out of it. And this was one month before demo day, when the companies needed to be nailing there products, propositions and pitches.

Rick and I were walking the floor, checking in on the companies, and found that one of the engineers in AthletePath, a startup focused on community and services for cyclists, runners and crazy triatheletes, had found a 'so-bad-its-awesome' video of a [cyclocross athlete eating it during a competition](https://www.youtube.com/watch?v=bEGAIYKTZ9w) and embedded it in Athletepath's 404 page.

With that simple ship, we realized that he'd not just found a video that was true and authentic to what they were all about as a company - he'd stumbled onto the perfect way to precisely and emotionally represent the feeling of a surprise bad experience with a service you loved. No-one else in the program had tackled the 404 page in quite the same way - or given it much thought. Most had default pages - those 404 pages that blame the victim ("you've arrived on this page in error") rather than take responsibility ("whoops - we let you down"). When you spend all your time thinking about what your service is, you can forget to think about what it isn't - and that was when the idea came to us.

On the spot, we announced the 404 contest - a 24 hour competition for the best 404 page, as decided by a vote of the participating startups and mentors. 

I described it as a chance to make real the 'hole in your heart' that would be left when that thing you love was taken away. A chance to use a little detail to reinforce their vision - and to reassure their customers that the people behind the thing they loved really cared about them and their experience. Our startups had spent two months laser-focused on what they were - for twenty-four hours, we asked them to focus on what they WEREN'T. 

The energy in the place went from zero to ridiculous. I remember the buzz of conversation, the whir of rolling chairs and tabletops being cleared. Everyone was super crisp, excited, and engaged. We heard laughter again - nervous quiet then genuine and loud. Good constructive arguing. And surprise - "taking people's eyes off the ball" by thinking about what they were NOT forced  important clarifying conversations for founder teams around issues they'd been consciously and unconsciously struggling with for weeks. 

It's fair to say that that contest spurred more forward progress in twenty-four hours than we'd seen in the two previous weeks.

The results ranged from inspiring and heartfelt to funny to genuinely useful. When the vote was taken - loudly, good naturedly and with surprising conviction - the "why" something won became as important as what had one, as we talked about mission, vision and expression. The 404 contest was a communal bonding event worth every penny of the $404 dollar prize we awarded to the winners - who promptly used their winnings to buy everyone drinks.

Best of all, the playful intensity cleared all the bullshit out of the room. People were exhausted, but they were in this together now, in a way they hadn't been before, and the energy level kicked up just in time for the final month of the program. 

The 404 contest transformed PIE from a zero-sum game of who was going to "win" the program to a community rooting for each other to kick ass. And along the way became a PIE tradition.

**Comment by turoczy** [comment]
Added to notes/logistics here: https://github.com/piepdx/pie-cookbook/blob/master/notes/logistics/404-contest.md 

Closing this issue.
